# Configuration file: config.yaml
title: Webviz-4D Drogon                              # Customize
 
shared_settings:
    field_names: [Drogon]
    sumo_case: 
    fmu_directory:                                  # Customize 
    label: Drogon                                   # Customize
    
    observed_maps: 
        realization_names: [realization-0]                  
        iteration_names: [iter-0]                   # Customize    
        map_directories: [share/observations/maps]          
        attributes: ['*'] 
        surface_names: ['*']
        time_intervals: ['*'] 

    simulated_maps: 
        realization_names: [realization-*]      
        iteration_names: [iter-*, pred]             # Customize        
        map_directories: [share/results/maps]     
        rms_polygons: [share/results/polygons]
        attributes: ['*'] 
        surface_names: ['*']
        time_intervals: ['*']   
        
    aggregated_maps:
        map_directories: ["statistics"]   
        attributes: ['*'] 
        surface_names: ['*']
        time_intervals: ['*']
        
    additional_maps:                                # Customize
        map_directory: 
        map_type: observed 
        map_format: fmu            
         
    basic_well_layers: 
        planned: Planned wells
        drilled_wells: Drilled wells                        
        reservoir_section: Reservoir sections              
        active_production:                          # Customize
        active_injection:                           # Customize
        
    additional_well_layers:      
        production: Producers                               
        production_start:                           # Customize
        production_completed:          
        injection: Injectors                                
        injection_start:                            # Customize                   
        injection_completed: 
         
    zone_polygon_layers: 
        faults: 
            tagname: gl_faultlines_extract_postprocess
            label: Faults 
            format: csv  
        goc: 
            tagname: field_outline_goc 
            label: GOC
            format: csv   
        fwl: 
            tagname: field_outline_fwl
            label: FWL
            format: csv    
            
    additional_polygon_layers:                      # Customize
        prm:
            label: PRM receivers 
            tagname: prm
            format: csv
        injectites:  
            label: Injectites                  
            tagname: injectites 
            format: csv 
         
    well_data: &well_data ./well_data 
    top_reservoir:                                  # Customize
        directory: share/results
        iteration: iter-0
        realization: realization-0
        maps_directory: maps
        map_name: topvolantis
        map_tagname: ds_extract_geogrid.gri
        polygons_directory: polygons
        polygon_name: topvolantis
        
    production_data: &production_data ./production_data   
    polygon_data: &polygon_data ./polygon_data  
    polygon_mapping_file: &polygon_mapping_file ./polygon_mapping.csv       
    colormap_data: &colormap_data ../colormaps/     
    selector_file: &selector_file ./selectors.yaml                
    surface_metadata_file: &surface_metadata_file ./surface_metadata.csv
    surface_scaling_file: &surface_scaling_file ./surface_scaling.csv
    settings_file: &settings_file ./settings.yaml 
    interval_mode: &interval_mode "normal"    
    prod_data_intervals: all    
         
# ------------------------------
options:
  menu:
    show_logo: true
    bar_position: left
    drawer_position: left
    initially_pinned: true
    initially_collapsed: true

# ------------------------------
layout:
  - section: Webviz-4D 2024.02  
    content:
      # -----------------------------         
      - page: Front page 
        icon: home
        content:  
          - Markdown: 
              markdown_file: ../front_page.md  
              
      # ------------------------------
      - group: Information
        icon: info_circle
        content:    
          - page: Webviz-4D
            content:   
              - EmbedPdf:  
                  pdf_file: ./webviz-4d.pdf
                  
          - page: How was this made
            content:
              - SyntaxHighlighter:
                  filename: ./config.yaml 
              - SyntaxHighlighter:
                  filename: ./settings.yaml  
                  
      # -------------------------------
      - group: Timelapse maps
        icon: layers
        content:    
 
          - page: Observed and simulated maps
            content:
              - SurfaceViewer4D: 
                  well_data: *well_data               
                  production_data: *production_data
                  polygon_data: *polygon_data 
                  polygon_mapping_file: *polygon_mapping_file      
                  colormap_data: *colormap_data     
                  selector_file: *selector_file 
                  surface_metadata_file: *surface_metadata_file
                  surface_scaling_file: *surface_scaling_file
                  settings_file: *settings_file 
                  interval_mode: *interval_mode                   
                  
                  map1_defaults:
                    attribute: relai_mean               # Customize 
                    name: volon                         # Customize
                    map_type: observed                          # Customize
                    iteration: ---                              # Customize
                    realization: ---                 # Customize   
                    interval: 2020-07-01-2018-01-01  
                  map2_defaults: 
                    attribute: relai_mean               # Customize 
                    name: volon                          # Customize
                    map_type: simulated                         # Customize
                    iteration: iter-0                              # Customize
                    realization: realization-0                  # Customize
                    interval: 2020-07-01-2018-01-01
                  map3_defaults:
                    attribute: average_swat                   # Customize
                    name: volon                          # Customize 
                    map_type: simulated                         # Customize
                    iteration: iter-0                              # Customize
                    realization: realization-0                  # Customize
                    interval: 2020-07-01-2018-01-01       # Customize
                                     
          - page: Observed maps
            content:
              - SurfaceViewer4D: 
                  well_data: *well_data               
                  production_data: *production_data
                  polygon_data: *polygon_data  
                  polygon_mapping_file: *polygon_mapping_file     
                  colormap_data: *colormap_data     
                  selector_file: *selector_file 
                  surface_metadata_file: *surface_metadata_file
                  surface_scaling_file: *surface_scaling_file
                  settings_file: *settings_file
                  interval_mode: *interval_mode                   
                  
                  map1_defaults: 
                    attribute: amplitude_mean              # Customize  
                    name: topvolantis                                 # Customize
                    map_type: observed                          # Customize
                    iteration: ---                              # Customize
                    realization: ---                  # Customize
                    interval: 2018-07-01-2018-01-01
                  map2_defaults: 
                    attribute: amplitude_mean                         # Customize
                    name: topvolantis                                 # Customize 
                    map_type: observed                          # Customize
                    iteration: ---                              # Customize
                    realization: ---                  # Customize   
                    interval: 2019-07-01-2018-01-01  
                  map3_defaults:
                    attribute: amplitude_mean                         # Customize 
                    name: topvolantis                                 # Customize
                    map_type: observed                          # Customize 
                    iteration: ---                              # Customize   
                    realization: ---                  # Customize
                    interval: 2020-07-01-2018-01-01     
 

      # -------------------------------
      - group: Well overviews
        icon: table_chart
        content:    
 
          - page: Wellbore overview  
            content:
                - DataTable:
                      csv_file: ../well_data/wellbore_overview.csv  
                      sorting: True
                      filtering: True  
                      
          - page: Production/injection overview 
            content:
                - DataTable:
                      csv_file: ../production_data/production_overview.csv  
                      sorting: True
                      filtering: True                        
                                        
      # -------------------------------
      - group: Production/injection plots
        icon: timeline
        content:    
 
          - page: Production plots  
            content:
                - TablePlotter:
                    csv_file: ../production_data/production_fluid_table.csv
                    plot_options:
                      x: 4D_interval
                      y: Volumes
                      type: bar   
                      color: Fluid
                      barmode: group
                      facet_col: Well
                    filter_cols:
                      - Well  
                      - 4D_interval
                      - Fluid  
                    filter_defaults: 
                      Well: [A-1]                                   # Customize
                    column_color_discrete_maps:
                      Fluid:
                         Produced_Oil_[kSm3]: '#00fa00'
                         Produced_Gas_[MSm3]: '#fa0000'
                         Produced_Water_[km3]: '#0000fa'  
                    lock: True                     

          - page: Injection plots  
            content:
                - TablePlotter:
                    csv_file: ../production_data/injection_fluid_table.csv
                    plot_options:
                      x: 4D_interval
                      y: Volumes
                      type: bar   
                      color: Fluid
                      barmode: group
                      facet_col: Well
                    filter_cols:
                      - Well  
                      - 4D_interval
                      - Fluid  
                    filter_defaults: 
                      Well: [A-5]                                  # Customize
                    column_color_discrete_maps:
                      Fluid:
                         Injected_Gas_[MSm3]: '#fa0000'
                         Injected_Water_[km3]: '#0000fa'  
                    lock: True          

      # -------------------------------
      - group: Production/injection volumes
        icon: table_chart
        content:    
 
          - page: Oil production volumes [kSm3] 
            content:
                - DataTable:
                      csv_file: ../production_data/BORE_INC_OIL_VOL.csv  
                      sorting: True
                      filtering: True                  

          - page: Gas production volumes [MSm3]
            content:
                - DataTable:
                      csv_file: ../production_data/BORE_INC_GAS_VOL.csv  
                      sorting: True
                      filtering: True 
                  
          - page: Water production volumes [km3]
            content:        
                - DataTable:
                      csv_file: ../production_data/BORE_INC_WAT_VOL.csv  
                      sorting: True
                      filtering: True      
                  
          - page: Water injection volumes [km3]  
            content:
                - DataTable:
                      csv_file: ../production_data/BORE_INC_WI_VOL.csv  
                      sorting: True
                      filtering: True 
                                                            
