attribute_settings:  
    default_colormap: seismic_r   
    
    amplitude_mean:
        color:   seismic_r
        min:  -0.03
        max:   0.03
    amplitude_rms:
        color:   inferno
        min:  0
        max:  0.03
    relai_mean:
        color:   seismic_r
        min:  -0.03
        max:   0.03
    average_pressure:
        color:   seismic_r  
        min:   -5
        max:    5     
    oilthickness:
        color:   seismic_r
        min:    -5
        max:     5
    average_sgas:
        color:   seismic_r 
        min: -0.5
        max:  0.5   
    average_soil:
        color:   seismic_r 
        min: -0.5
        max:  0.5  
    average_swat:
        color:   seismic_r 
        min: -0.5
        max:  0.5   
    oilthickness:
        color:   seismic_r 
        min: -1
        max:  1        
        
well_colors:
    default: black
    oil_open: lime
    oil_production: green
    gas_open: salmon
    gas_production: red
    gas_injection:  magenta
    water_injection: blue
    wag_injection: pink   
    planned: purple   
    
polygon_colors:
    faults: black   
    
prod_data_intervals: 
    
 
